### ISSUE TITLE
Cauldron remapping

### ISSUE THREAD

**Issue by iBars** [MCTCP/TerrainControl#317] opened 2015-01-11 23:19 UTC
Hello. Please, link (or tell) me how to port plugins using NMS to Cauldron. Big thanks!

**Comment by rutgerkok** [comment] 2015-01-12 18:41
It should just work fine out of the box... Code your plugin for CraftBukkit, let it run on Cauldron. Cauldron automatically remaps plugins.

Most reflection (like `nmsClass.getDeclaredField("b")`) won't work, as the string "b" is not remapped. You'll have to loop through the fields (`nmsClass.getFields()`) and search for the field based on other criteria, like the type.

Closing this tcket, as it's not a bug report or a feature request.

**Closed by rutgerkok** 2015-01-12 18:41 UTC

**Comment by iBars** [comment] 2015-01-12 22:35
What you can say about tutorial from agaricusb?
http://bukkit.org/threads/tutorial-advanced-how-to-develop-plugins-using-mcp-for-nms-via-asm-remapping.131060/
I ask you because you are one from some people who made plugin compatible with MCPC+/Cauldron. Citizens2 was recoded by Cauldron developer, ProtocolLib was abandoned by aadnk... Only you stay
