### ISSUE TITLE
 The link to download better bob does not work

### ISSUE THREAD

**Issue by FirevskyyTM** [MCTCP/TerrainControl#525] opened 2017-04-19 08:13 UTC
Give me link the download Better Bob, please.

**Comment by rutgerkok** [comment] 2017-04-21 17:32
The old forums on BukkitDev are gone, and Dropbox also killed all direct links to public folders. It is not surprising that some old tools are gone...

Closing this, as it is not a bug in TerrainControl.

**Closed by rutgerkok** 2017-04-21 17:32 UTC
