### ISSUE TITLE
Rarity cannot be set to 0.

### ISSUE THREAD

**Issue by strongholdfinder** [MCTCP/TerrainControl#315] opened 2014-12-10 22:42 UTC
The biome rarity cannot be set to 0. This can be very troublesome when I'm trying to make themed maps. Whether intended or not, please allow it to be 0.

**Comment by rutgerkok** [comment] 2015-02-16 13:25
Closing this, as this is not a bug that's going to be fixed.

**Closed by rutgerkok** 2015-02-16 13:25 UTC
