### ISSUE TITLE
Internal error - TerrainControl

### ISSUE THREAD

**Issue by Isaacey** [MCTCP/TerrainControl#350] opened 2015-08-23 02:24 UTC
I'm trying to create a TerrainControl world with multiverse but get the error "An internal error occured while attempting to perform this command"

I have the latest version or TerrainControl and Multiverse. I'm not sure if you need other plugins to make TerrainControl or any other dependencies?
Here are my start up log.
http://pastebin.com/4kJD7Zjm

Thanks for reading hope I get an solution for this

**Comment by rutgerkok** [comment] 2015-08-23 08:36
You'll also need the latest version of Spigot. You're running 1.8.0 (`Starting minecraft server version 1.8`), while the latest version is already at 1.8.8.

**Comment by rutgerkok** [comment] 2015-08-26 08:38
Closing this issue, as I'm almost certain that this is a version mismatch, not a bug in TC.

Feel free to still comment here, this thread is still open for replies and I'm happy to help you.

**Closed by rutgerkok** 2015-08-26 08:38 UTC
