### ISSUE TITLE
Error when loading.

### ISSUE THREAD

**Issue by Livaco** [MCTCP/TerrainControl#557] opened 2017-12-03 19:58 UTC
[19:57:43 ERROR]: Error occurred while enabling TerrainControl v2.8.2-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_11_R1/WorldGenFactory
        at com.khorn.terraincontrol.bukkit.TXPlugin.onEnable(TXPlugin.java:86) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_11_R1.WorldGenFactory
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        ... 9 more

**Comment by rutgerkok** [comment] 2017-12-09 20:53
Normally, I would suggest going to the build server, which contains the most up-to-date version of TerrainControl. However, it seems to have problems, so I uploaded the latest file to my Dropbox:

https://www.dropbox.com/s/orcbx6itax8frmp/TerrainControl.jar?dl=0

Could you test whether this file works fine?

(I have closed this issue since I'm 99% sure that is the cause of your crash. Feel free to comment here if that doesn't fix your problem.)

**Closed by rutgerkok** 2017-12-09 20:53 UTC
